aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  s3:
    default-bucket-name: nomkhonwaan-com

graphiql:
  mapping: /

line.bot:
  channel-token: ${LINE_BOT_CHANNEL_TOKEN}
  channel-secret: ${LINE_BOT_CHANNEL_SECRET}
  handler.path: /callback

security:
  oauth2:
    resource:
      user-info-uri: https://nomkhonwaan.auth0.com/userinfo

spring:
  data:
    mongodb.uri: ${MONGODB_URI:mongodb://localhost/nomkhonwaan_com}
