auth0:
    domain: nomkhonwaan.auth0.com
    audience: https://nomkhonwaan.auth0.com/api/v2/
    client-id: ${AUTH0_CLIENT_ID}
    client-secret: ${AUTH0_CLIENT_SECRET}

axon:
  extensions:
    mongo:
      databaseName: nomkhonwaan_com

graphiql:
  mapping: /

line:
  bot:
    channel-token: ${LINE_BOT_CHANNEL_TOKEN}
    channel-secret: ${LINE_BOT_CHANNEL_SECRET}
    handler:
      path: /chatbot/line/callback
  notify:
    url: https://notify-api.line.me
    token: ${LINE_NOTIFY_TOKEN}

security:
  oauth2:
    resource:
      user-info-uri: https://nomkhonwaan.auth0.com/userinfo

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost/nomkhonwaan_com}
